### PR TITLE
Removing expired report data on regular monthly schedule

### PR DESCRIPTION
**Pull request by dccurtis**
**Overview**
This is a continuation of PR https://github.com/project-koku/masu/pull/119.  Now This same logic kicked off by the `DEL /api/v1/expired_data` call will be ran in a beat schedule that runs on the first of the month.  At midnight the expired report data will be cleared.

A new environment variable `REMOVE_EXPIRED_REPORT_DATA_ON_DAY` was added so we can adjust what day of the month report data cleaning will take place.  If it is set to 0 then report cleaning will be disabled.

Note: I was having trouble setting `crontab` to run on a specific day_of_month as well as specying hour and minutes.  If I find a solution to that I would much prefer to use crontab to just queue a single task at that specific time of the month.  I will surely update this if I find the answer but for now this seems to work.

**Testing**

**NOTE** It's important to know that the worker doing the cleaning is operating on the worker's host date and time.  That being said to test this you will have to set `REMOVE_EXPIRED_REPORT_DATA_ON_DAY` to the current actual day and not necessarily the one set with `MASU_DATE_OVERRIDE` 

Functional test plan:
1. Set env to day 0 to verify that removal task is not scheduled:
2. Unset the env and verify that the cleaning day is defaulted to the first of the month:
3. Test to make sure the cleaning is done at midnight

Results:
[beat_scheudle_remove_data_ut.txt](https://github.com/project-koku/masu/files/2254756/beat_scheudle_remove_data_ut.txt)

### CODE REVIEW

**Comment by dccurtis** [comment]
Theres probably a change needed for the OpenShift template.  I'll do that next but figured this was enough to get out for review.

**Comment by dccurtis** [comment]
What sort of configuration items did you have in mind?  I could only thing of setting the specific date and time.  Was there something else?

**Comment by blentz** [comment]
@dccurtis - In short, it should be an Ops decision on what the purge schedule should be, not a hard-coded setting decided by the project developers. 

So, we'd need basically the full crontab-esque range of options to allow an admin to decide whether the purge happens daily, weekly, monthly, or annually, and the precise timing of it (minute, hour, day, day-of-week, day-of-month).

**Comment by dccurtis** [comment]
oh I see.  Yeah need to resolve the problems I having with `crontab` to do that.  For now just focusing on the user story requirements for pilot to be working with 3 months of data for the defaults.

**Pull request merged**
